// src/components/vue/InputField.vue
<template>
    <div class="form-group row">
        <label :for="id" class="col-3 col-form-label">{{ label }} *</label>
        <div class="col-9">
            <input class="form-control" :type="type" :placeholder="placeholder" :id="id" v-model="value">
        </div>
    </div>
</template>

<script>
export default {
    props: {
        id: String,
        label: String,
        placeholder: String,
        type: {
            type: String,
            default: 'text'
        },
        value: String
    }
}
</script>

// src/components/InputField.tsx
import { createSignal } from 'solid-js';

type Props = {
  id: string,
  label: string,
  placeholder: string,
  type?: string
};

export const InputField = (props: Props) => {
  const [value, setValue] = createSignal('');

  return (
    <div class="form-group row mt-2">
      <label for={props.id} class="col-3 col-form-label">{props.label} *</label>
      <div class="col-9">
        <input class="form-control" type={props.type || 'text'} placeholder={props.placeholder} id={props.id} value={value()} onChange={(e: Event) => setValue((e.target as HTMLInputElement).value)}/>
      </div>
    </div>
  );
};
